---
version: 2
executorType: docker
containerInfo:
  - image: jimmycuadra/rust:latest
stages:
  build:
    workDir: /source
    steps:
      - type: shell
        shell: /bin/bash
        command: apt-get update
      - type: shell
        shell: /bin/bash
        command: apt-get install openssh-client -y
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: cargo build
